# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

impurity_reduction <- function(father_bad, father_good, left_bad, left_good, right_bad, right_good) {
    .Call(`_RcppA_impurity_reduction`, father_bad, father_good, left_bad, left_good, right_bad, right_good)
}

