// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// impurity_reduction
double impurity_reduction(int father_bad, int father_good, int left_bad, int left_good, int right_bad, int right_good);
RcppExport SEXP _RcppA_impurity_reduction(SEXP father_badSEXP, SEXP father_goodSEXP, SEXP left_badSEXP, SEXP left_goodSEXP, SEXP right_badSEXP, SEXP right_goodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type father_bad(father_badSEXP);
    Rcpp::traits::input_parameter< int >::type father_good(father_goodSEXP);
    Rcpp::traits::input_parameter< int >::type left_bad(left_badSEXP);
    Rcpp::traits::input_parameter< int >::type left_good(left_goodSEXP);
    Rcpp::traits::input_parameter< int >::type right_bad(right_badSEXP);
    Rcpp::traits::input_parameter< int >::type right_good(right_goodSEXP);
    rcpp_result_gen = Rcpp::wrap(impurity_reduction(father_bad, father_good, left_bad, left_good, right_bad, right_good));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppA_impurity_reduction", (DL_FUNC) &_RcppA_impurity_reduction, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
