# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCEuropeanOptionPricer <- function(expiry = 0.5, strike = 100, spot = 95, vol = 0.2, r = 0.06, number_of_paths = 1000000L, seed = 0L) {
    .Call(`_OptionPricer2_MCEuropeanOptionPricer`, expiry, strike, spot, vol, r, number_of_paths, seed)
}

rcpp_hello <- function() {
    .Call(`_OptionPricer2_rcpp_hello`)
}

